#!/bin/bash
#sudo apt-get install gcc-mingw-w64-x86-64
CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ GOOS=windows GOARCH=amd64 go build -o work_motivated.exe -ldflags="-s -w" main.go 
